import { createAnimations } from "@tamagui/animations-react-native";
import { createInterFont } from "@tamagui/font-inter";
import { shorthands } from "@tamagui/shorthands";
import { tokens as defaultTokens } from "@tamagui/config/v3";
import { createTamagui, createTokens } from "tamagui";

const animations = createAnimations({
  bouncy: {
    type: "spring",
    damping: 10,
    mass: 0.9,
    stiffness: 100,
  },
  lazy: {
    type: "spring",
    damping: 20,
    stiffness: 60,
  },
  quick: {
    type: "spring",
    damping: 20,
    stiffness: 250,
  },
  medium: {
    type: "spring",
    damping: 15,
    stiffness: 120,
  },
  slow: {
    type: "spring",
    damping: 20,
    stiffness: 60,
  },
  tooltip: {
    type: "spring",
    damping: 10,
    mass: 0.9,
    stiffness: 100,
  },
});

const headingFont = createInterFont({
  size: {
    1: 11,
    2: 12,
    3: 13,
    4: 14,
    5: 15,
    6: 16,
    7: 18,
    8: 20,
    9: 24,
    10: 28,
    11: 32,
    12: 36,
    13: 40,
    14: 48,
    15: 56,
    16: 64,
    true: 16,
  },
  weight: {
    4: "400",
    5: "500",
    6: "600",
    7: "700",
  },
  letterSpacing: {
    4: 0,
    5: 0,
    6: -0.5,
    7: -0.5,
    8: -1,
    9: -1,
    10: -2,
  },
  face: {
    400: { normal: "System" },
    500: { normal: "System" },
    600: { normal: "System" },
    700: { normal: "System" },
  },
});

const bodyFont = createInterFont(
  {
    size: {
      1: 11,
      2: 12,
      3: 13,
      4: 14,
      5: 15,
      6: 16,
      7: 18,
      8: 20,
      9: 24,
      10: 28,
      true: 14,
    },
    weight: {
      4: "400",
      5: "500",
      6: "600",
      7: "700",
    },
    face: {
      400: { normal: "System" },
      500: { normal: "System" },
      600: { normal: "System" },
      700: { normal: "System" },
    },
  },
  {
    sizeSize: (size: number) => Math.round(size * 1.1),
    sizeLineHeight: (size: number) => Math.round(size * 1.1 + 10),
  }
);

const monoFont = createInterFont({
  size: {
    1: 11,
    2: 12,
    3: 13,
    4: 14,
    5: 15,
    6: 16,
    7: 18,
    8: 20,
    true: 14,
  },
  face: {
    400: { normal: "JetBrainsMono" },
    700: { normal: "JetBrainsMono" },
  },
});

const cosmicTokens = createTokens({
  ...defaultTokens,
  size: {
    ...defaultTokens.size,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  color: {
    ...defaultTokens.color,
    darkBackground: "#0a0a0f",
    darkBackgroundAlt: "#0d0d14",
    darkSurface: "#13131a",
    darkSurfaceAlt: "#1a1a24",
    darkSurfaceMuted: "#22222e",
    darkSurfaceElevated: "#1e1e2a",
    darkText: "#f0f0f5",
    darkTextMuted: "#b8b8c8",
    darkTextSubtle: "#6b6b80",
    darkBorder: "rgba(255, 255, 255, 0.08)",
    darkBorderSubtle: "rgba(255, 255, 255, 0.04)",
    darkPrimary: "#7c5cff",
    darkPrimaryMuted: "rgba(124, 92, 255, 0.15)",
    darkPrimaryLight: "#9d85ff",
    darkSecondary: "#00d9ff",
    darkSecondaryMuted: "rgba(0, 217, 255, 0.15)",
    darkSuccess: "#00e676",
    darkSuccessMuted: "rgba(0, 230, 118, 0.12)",
    darkSuccessLight: "#69f0ae",
    darkWarning: "#ffab40",
    darkWarningMuted: "rgba(255, 171, 64, 0.12)",
    darkDanger: "#ff5252",
    darkDangerMuted: "rgba(255, 82, 82, 0.12)",
    darkAccent: "#e040fb",
    darkAccentMuted: "rgba(224, 64, 251, 0.15)",
    darkAccentLight: "#ea80fc",
    darkPlaceholder: "#4a4a5a",
    darkDisabled: "#3a3a4a",
    darkGlow: "rgba(124, 92, 255, 0.4)",
    darkGlowSubtle: "rgba(124, 92, 255, 0.2)",
    darkCard: "rgba(19, 19, 26, 0.8)",
    darkCardBorder: "rgba(255, 255, 255, 0.06)",
    darkOverlay: "rgba(0, 0, 0, 0.7)",

    lightBackground: "#f8f9fc",
    lightBackgroundAlt: "#f0f1f5",
    lightSurface: "#ffffff",
    lightSurfaceAlt: "#f5f6fa",
    lightSurfaceMuted: "#ebedf2",
    lightSurfaceElevated: "#ffffff",
    lightText: "#0f0f1a",
    lightTextMuted: "#3a3a4f",
    lightTextSubtle: "#6b6b80",
    lightBorder: "rgba(0, 0, 0, 0.08)",
    lightBorderSubtle: "rgba(0, 0, 0, 0.04)",
    lightPrimary: "#6b4eff",
    lightPrimaryMuted: "rgba(107, 78, 255, 0.1)",
    lightPrimaryLight: "#8b72ff",
    lightSecondary: "#00b8d9",
    lightSecondaryMuted: "rgba(0, 184, 217, 0.1)",
    lightSuccess: "#00c853",
    lightSuccessMuted: "rgba(0, 200, 83, 0.1)",
    lightSuccessLight: "#69f0ae",
    lightWarning: "#ff9100",
    lightWarningMuted: "rgba(255, 145, 0, 0.1)",
    lightDanger: "#ff1744",
    lightDangerMuted: "rgba(255, 23, 68, 0.1)",
    lightAccent: "#d500f9",
    lightAccentMuted: "rgba(213, 0, 249, 0.1)",
    lightAccentLight: "#e040fb",
    lightPlaceholder: "#9ca3af",
    lightDisabled: "#d1d5db",
    lightGlow: "rgba(107, 78, 255, 0.3)",
    lightGlowSubtle: "rgba(107, 78, 255, 0.15)",
    lightCard: "rgba(255, 255, 255, 0.9)",
    lightCardBorder: "rgba(0, 0, 0, 0.06)",
    lightOverlay: "rgba(0, 0, 0, 0.5)",
  },
  space: {
    ...defaultTokens.space,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    ...defaultTokens.radius,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
});

const darkTheme = {
  background: cosmicTokens.color.darkBackground,
  backgroundHover: cosmicTokens.color.darkBackgroundAlt,
  backgroundPress: cosmicTokens.color.darkSurface,
  backgroundFocus: cosmicTokens.color.darkSurface,
  backgroundStrong: cosmicTokens.color.darkSurface,
  backgroundTransparent: "transparent",

  color: cosmicTokens.color.darkText,
  colorHover: cosmicTokens.color.darkText,
  colorPress: cosmicTokens.color.darkTextMuted,
  colorFocus: cosmicTokens.color.darkText,
  colorTransparent: "transparent",

  borderColor: cosmicTokens.color.darkBorder,
  borderColorHover: cosmicTokens.color.darkBorderSubtle,
  borderColorFocus: cosmicTokens.color.darkPrimary,
  borderColorPress: cosmicTokens.color.darkPrimary,

  placeholderColor: cosmicTokens.color.darkPlaceholder,

  primary: cosmicTokens.color.darkPrimary,
  primaryMuted: cosmicTokens.color.darkPrimaryMuted,
  primaryLight: cosmicTokens.color.darkPrimaryLight,
  secondary: cosmicTokens.color.darkSecondary,
  secondaryMuted: cosmicTokens.color.darkSecondaryMuted,
  success: cosmicTokens.color.darkSuccess,
  successMuted: cosmicTokens.color.darkSuccessMuted,
  successLight: cosmicTokens.color.darkSuccessLight,
  warning: cosmicTokens.color.darkWarning,
  warningMuted: cosmicTokens.color.darkWarningMuted,
  danger: cosmicTokens.color.darkDanger,
  dangerMuted: cosmicTokens.color.darkDangerMuted,
  accent: cosmicTokens.color.darkAccent,
  accentMuted: cosmicTokens.color.darkAccentMuted,
  accentLight: cosmicTokens.color.darkAccentLight,

  surface: cosmicTokens.color.darkSurface,
  surfaceAlt: cosmicTokens.color.darkSurfaceAlt,
  surfaceMuted: cosmicTokens.color.darkSurfaceMuted,
  surfaceElevated: cosmicTokens.color.darkSurfaceElevated,

  textMuted: cosmicTokens.color.darkTextMuted,
  textSubtle: cosmicTokens.color.darkTextSubtle,

  disabled: cosmicTokens.color.darkDisabled,
  glow: cosmicTokens.color.darkGlow,
  glowSubtle: cosmicTokens.color.darkGlowSubtle,
  card: cosmicTokens.color.darkCard,
  cardBorder: cosmicTokens.color.darkCardBorder,
  overlay: cosmicTokens.color.darkOverlay,

  gradientPrimaryStart: "#7c5cff",
  gradientPrimaryEnd: "#5c3dff",
  gradientAccentStart: "#e040fb",
  gradientAccentEnd: "#7c5cff",
  gradientCosmicStart: "#7c5cff",
  gradientCosmicMid: "#e040fb",
  gradientCosmicEnd: "#00d9ff",

  dialogGradientStart: "#1a1a1a",
  dialogGradientMid: "#252525",
  dialogGradientEnd: "#1f1f1f",
  dialogOverlay: "rgba(0,0,0,0.85)",
  dialogBorder: "rgba(255,255,255,0.12)",
  dialogText: "#ffffff",
  dialogTextMuted: "#a0a0a0",
  dialogButtonBorder: "rgba(255,255,255,0.15)",
  dialogButtonHover: "rgba(255,255,255,0.08)",
  dialogHandle: "rgba(255,255,255,0.3)",

  shadowColor: "#000000",
  shadowColorStrong: "rgba(0, 0, 0, 0.4)",

  switchThumb: "#ffffff",
};

const lightTheme = {
  background: cosmicTokens.color.lightBackground,
  backgroundHover: cosmicTokens.color.lightBackgroundAlt,
  backgroundPress: cosmicTokens.color.lightSurface,
  backgroundFocus: cosmicTokens.color.lightSurface,
  backgroundStrong: cosmicTokens.color.lightSurface,
  backgroundTransparent: "transparent",

  color: cosmicTokens.color.lightText,
  colorHover: cosmicTokens.color.lightText,
  colorPress: cosmicTokens.color.lightTextMuted,
  colorFocus: cosmicTokens.color.lightText,
  colorTransparent: "transparent",

  borderColor: cosmicTokens.color.lightBorder,
  borderColorHover: cosmicTokens.color.lightBorderSubtle,
  borderColorFocus: cosmicTokens.color.lightPrimary,
  borderColorPress: cosmicTokens.color.lightPrimary,

  placeholderColor: cosmicTokens.color.lightPlaceholder,

  primary: cosmicTokens.color.lightPrimary,
  primaryMuted: cosmicTokens.color.lightPrimaryMuted,
  primaryLight: cosmicTokens.color.lightPrimaryLight,
  secondary: cosmicTokens.color.lightSecondary,
  secondaryMuted: cosmicTokens.color.lightSecondaryMuted,
  success: cosmicTokens.color.lightSuccess,
  successMuted: cosmicTokens.color.lightSuccessMuted,
  successLight: cosmicTokens.color.lightSuccessLight,
  warning: cosmicTokens.color.lightWarning,
  warningMuted: cosmicTokens.color.lightWarningMuted,
  danger: cosmicTokens.color.lightDanger,
  dangerMuted: cosmicTokens.color.lightDangerMuted,
  accent: cosmicTokens.color.lightAccent,
  accentMuted: cosmicTokens.color.lightAccentMuted,
  accentLight: cosmicTokens.color.lightAccentLight,

  surface: cosmicTokens.color.lightSurface,
  surfaceAlt: cosmicTokens.color.lightSurfaceAlt,
  surfaceMuted: cosmicTokens.color.lightSurfaceMuted,
  surfaceElevated: cosmicTokens.color.lightSurfaceElevated,

  textMuted: cosmicTokens.color.lightTextMuted,
  textSubtle: cosmicTokens.color.lightTextSubtle,

  disabled: cosmicTokens.color.lightDisabled,
  glow: cosmicTokens.color.lightGlow,
  glowSubtle: cosmicTokens.color.lightGlowSubtle,
  card: cosmicTokens.color.lightCard,
  cardBorder: cosmicTokens.color.lightCardBorder,
  overlay: cosmicTokens.color.lightOverlay,

  gradientPrimaryStart: "#6b4eff",
  gradientPrimaryEnd: "#5530ff",
  gradientAccentStart: "#d500f9",
  gradientAccentEnd: "#6b4eff",
  gradientCosmicStart: "#6b4eff",
  gradientCosmicMid: "#d500f9",
  gradientCosmicEnd: "#00b8d9",

  dialogGradientStart: "#ffffff",
  dialogGradientMid: "#f5f5f5",
  dialogGradientEnd: "#fafafa",
  dialogOverlay: "rgba(0,0,0,0.5)",
  dialogBorder: "rgba(0,0,0,0.1)",
  dialogText: "#1a1a1a",
  dialogTextMuted: "#666666",
  dialogButtonBorder: "rgba(0,0,0,0.12)",
  dialogButtonHover: "rgba(0,0,0,0.05)",
  dialogHandle: "rgba(0,0,0,0.2)",

  shadowColor: "#6b4eff",
  shadowColorStrong: "rgba(107, 78, 255, 0.2)",

  switchThumb: "#ffffff",
};

export const config = createTamagui({
  defaultFont: "body",
  animations,
  shouldAddPrefersColorThemes: true,
  themeClassNameOnRoot: true,
  shorthands,
  fonts: {
    heading: headingFont,
    body: bodyFont,
    mono: monoFont,
  },
  themes: {
    dark: darkTheme,
    light: lightTheme,
    dark_Button: {
      ...darkTheme,
      background: darkTheme.primary,
      backgroundHover: darkTheme.primaryLight,
      backgroundPress: darkTheme.primaryMuted,
      color: "#ffffff",
    },
    light_Button: {
      ...lightTheme,
      background: lightTheme.primary,
      backgroundHover: lightTheme.primaryLight,
      backgroundPress: lightTheme.primaryMuted,
      color: "#ffffff",
    },
    dark_danger: {
      ...darkTheme,
      background: darkTheme.danger,
      backgroundHover: darkTheme.dangerMuted,
      backgroundPress: darkTheme.dangerMuted,
      color: "#ffffff",
    },
    light_danger: {
      ...lightTheme,
      background: lightTheme.danger,
      backgroundHover: lightTheme.dangerMuted,
      backgroundPress: lightTheme.dangerMuted,
      color: "#ffffff",
    },
    dark_success: {
      ...darkTheme,
      background: darkTheme.success,
      backgroundHover: darkTheme.successMuted,
      backgroundPress: darkTheme.successMuted,
      color: "#ffffff",
    },
    light_success: {
      ...lightTheme,
      background: lightTheme.success,
      backgroundHover: lightTheme.successMuted,
      backgroundPress: lightTheme.successMuted,
      color: "#ffffff",
    },
  },
  tokens: cosmicTokens,
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: "none" },
    pointerCoarse: { pointer: "coarse" },
  },
});

export type AppConfig = typeof config;

declare module "tamagui" {
  interface TamaguiCustomConfig extends AppConfig {}
}
